In [4]:
from ReliefF import ReliefF
import pandas as pd
import numpy as np
import pandas as pd
import numpy as np
from sklearn.svm import SVR
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest, RFE
from sklearn.feature_selection import chi2

In [5]:
dataset2 = pd.read_csv("megringaftertransfer.csv",delimiter=",")
dataset2.head()

Age    DBP  Obese     SBP    bmi  gender   hc  hyper  id  wc  whr
0   31  74.33      0  128.00  28.76       1  101      0   1  88   87
1   21  70.00      0  123.33  27.59       1  110      0   7  86   78
2   23  56.67      0   90.00  22.45       1  104      2   8  72   69
3   24  90.00      0  126.67  28.16       1  108      0  13  89   82
4   20  69.00      0  120.00  25.05       1  108      2  15  81   75

# RFE

In [6]:
array = dataset2.values
#Split dataset
#Sample vectors
X = array[:,0:11]
# Target vector (class labels) 
y = array[:,7] 
model = LogisticRegression()
rfe = RFE(model)
rfe = rfe.fit(X,y)
rfe.support_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default so

array([False, False, False, False, False,  True,  True,  True, False,
        True,  True])

In [7]:
rfe.ranking_
rfe.n_features_

5

In [8]:
rfe.ranking_

array([6, 5, 3, 2, 4, 1, 1, 1, 7, 1, 1])

In [9]:
from ReliefF import ReliefF
fs = ReliefF(n_neighbors=20, n_features_to_keep=3)
X_train = fs.fit_transform(X, y)
print("(No. of tuples, No. of Columns before ReliefF) : " +str(dataset2.shape)+
     "\n(No. of tuples, No. of Columns after ReliefF) : "+str(X_train.shape ) )   


(No. of tuples, No. of Columns before ReliefF) : (399, 11)
(No. of tuples, No. of Columns after ReliefF) : (399, 3)


In [10]:
print(X_train)

[[0. 1. 0.]
 [0. 1. 0.]
 [2. 1. 0.]
 ...
 [2. 0. 0.]
 [2. 0. 0.]
 [2. 0. 0.]]
